- name: default value
  hosts: localhost
  tasks:
    - name: print default value
      ansible.builtin.debug:
        msg: "tata {{product | default('cars') }}"


- name: words to upper case
  hosts: localhost
  vars:
    fruit: "mango"
  tasks:
    - name: changing the lower case into upper case
      ansible.builtin.debug:
        msg: "{{fruit | upper}}"

- name: words to lower case
  hosts: localhost
  vars:
    fruit: "mango"
  tasks:
    - name: changing upper case to lower case
      ansible.builtin.debug:
        msg: "{{fruit | lower}}"

        
- name: removing duplicates
  hosts: localhost
  vars:
    numbers: [5, 6, 4, 5, 6, 3, 6, 3]
  tasks:
    - name: remove duplicates
      ansible.builtin.debug:
        msg: "{{ numbers | unique }}"

