- name: insall packages
  hosts: web
  become: yes
  tasks:
    - name: install list below
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: latest
      loop:
        - mysql
        - nginx