- name: loops
  hosts: localhost
  tasks:
    - name: print list
      ansibl,builtin.debug: 
        msg: "we are going to install below items {{item}}"
      loops:
        - linux
        - git
        - ansible
