- name: install packages
  hosts: web
  become: yes
  tasks:
    - name: install list below
      ansible.builtin.dnf:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      loop:
        - { name: 'mysql', state: 'latest' }
        - { name: 'nginx', state: 'absent'}