- name: loops
  hosts: localhost
  tasks:
    - name: print list
      ansible.builtin.debug: 
        msg: "we are going to install below items {{ item }}"
      loop:
        - linux
        - git
        - ansible

